// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.1
// source: msg.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_AUTHREQ    Op = 0
	Op_AUTHEEPLY  Op = 1
	Op_CLOSEREQ   Op = 2
	Op_CLOSEREPLY Op = 3
	Op_MSGREQ     Op = 4
	Op_MSGREPLY   Op = 5
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "AUTHREQ",
		1: "AUTHEEPLY",
		2: "CLOSEREQ",
		3: "CLOSEREPLY",
		4: "MSGREQ",
		5: "MSGREPLY",
	}
	Op_value = map[string]int32{
		"AUTHREQ":    0,
		"AUTHEEPLY":  1,
		"CLOSEREQ":   2,
		"CLOSEREPLY": 3,
		"MSGREQ":     4,
		"MSGREPLY":   5,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

// todo 仅演示,正常线上一般添加version,checksum,msg 业务syn ack
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Len  int32  `protobuf:"varint,1,opt,name=len,proto3" json:"len,omitempty"`
	Op   Op     `protobuf:"varint,2,opt,name=op,proto3,enum=tcp_debug.api.Op" json:"op,omitempty"`
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *Msg) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_AUTHREQ
}

func (x *Msg) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x63, 0x70,
	0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x4e, 0x0a, 0x03, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6c, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x74, 0x63, 0x70, 0x5f, 0x64, 0x65, 0x62, 0x75, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x2a, 0x58, 0x0a, 0x02, 0x4f, 0x70,
	0x12, 0x0b, 0x0a, 0x07, 0x41, 0x55, 0x54, 0x48, 0x52, 0x45, 0x51, 0x10, 0x00, 0x12, 0x0d, 0x0a,
	0x09, 0x41, 0x55, 0x54, 0x48, 0x45, 0x45, 0x50, 0x4c, 0x59, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x43, 0x4c, 0x4f, 0x53, 0x45, 0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x43, 0x4c,
	0x4f, 0x53, 0x45, 0x52, 0x45, 0x50, 0x4c, 0x59, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x53,
	0x47, 0x52, 0x45, 0x51, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x53, 0x47, 0x52, 0x45, 0x50,
	0x4c, 0x59, 0x10, 0x05, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x32, 0x70, 0x67, 0x63, 0x6e, 0x2f, 0x74, 0x63, 0x70, 0x5f, 0x64, 0x65, 0x62,
	0x75, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_msg_proto_goTypes = []interface{}{
	(Op)(0),     // 0: tcp_debug.api.Op
	(*Msg)(nil), // 1: tcp_debug.api.Msg
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: tcp_debug.api.Msg.op:type_name -> tcp_debug.api.Op
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
